// <auto-generated />
namespace TripodReporter.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AddPolicyType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddPolicyType));
        
        string IMigrationMetadata.Id
        {
            get { return "201408272257325_AddPolicyType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
